"""empty message

Revision ID: 1f5fd24b5d56
Revises: None
Create Date: 2015-03-30 08:21:08.619358

"""

# revision identifiers, used by Alembic.
revision = '1f5fd24b5d56'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
